### ISSUE TITLE
Cyphon VM does not start the services

### ISSUE THREAD

**Issue by sachinjung** [cyphonmdr/cyphon#716]
Hi,
I have installed Cyphon from the latest ISO in VMware Workstation. System has 2 vCPU, 8GB RAM, 200GB HDD and 4 NIC (1 Bridge + 3 NAT) with DHCP enabled. Internet is working fine. I have accessed the system over SSHv2. Below is the result what I got.

root@CyphonSOC:/home/soc# systemctl status cyphon
● cyphon.service - Cyphon Service
   Loaded: loaded (/etc/systemd/system/cyphon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-10-03 15:58:39 UTC; 29s ago
  Process: 1146 ExecStart=/usr/local/bin/docker-compose up -d (code=exited, status=1/FAILURE)
  Process: 1056 ExecStartPre=/usr/local/bin/docker-compose pull --quiet --parallel (code=exited, status=0/SUCCESS)
 Main PID: 1146 (code=exited, status=1/FAILURE)

Oct 03 15:58:39 CyphonSOC docker-compose[1146]: <head><title>404 Not Found</title></head>
Oct 03 15:58:39 CyphonSOC docker-compose[1146]: <body bgcolor="white">
Oct 03 15:58:39 CyphonSOC docker-compose[1146]: <center><h1>404 Not Found</h1></center>
Oct 03 15:58:39 CyphonSOC docker-compose[1146]: <hr><center>nginx/1.10.3</center>
Oct 03 15:58:39 CyphonSOC docker-compose[1146]: </body>
Oct 03 15:58:39 CyphonSOC docker-compose[1146]: </html>
Oct 03 15:58:39 CyphonSOC systemd[1]: cyphon.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 15:58:39 CyphonSOC systemd[1]: Failed to start Cyphon Service.
Oct 03 15:58:39 CyphonSOC systemd[1]: cyphon.service: Unit entered failed state.
Oct 03 15:58:39 CyphonSOC systemd[1]: cyphon.service: Failed with result 'exit-code'.
root@CyphonSOC:/home/soc# systemctl start cyphon
Job for cyphon.service failed because the control process exited with error code. See "systemctl status cyphon.service" and "journalctl -xe" for details.
root@CyphonSOC:/home/soc#
root@CyphonSOC:/home/soc# systemctl status docker.service -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-10-03 15:58:26 UTC; 9min ago
     Docs: https://docs.docker.com
 Main PID: 837 (dockerd)
    Tasks: 18
   Memory: 123.7M
      CPU: 7.030s
   CGroup: /system.slice/docker.service
           ├─837 /usr/bin/dockerd -H fd://
           └─873 docker-containerd --config /var/run/docker/containerd/containerd.toml

Oct 03 15:58:25 CyphonSOC dockerd[837]: time="2020-10-03T15:58:25.810525862Z" level=warning msg="Your kernel does not support swap memory limit"
Oct 03 15:58:25 CyphonSOC dockerd[837]: time="2020-10-03T15:58:25.810762295Z" level=warning msg="Your kernel does not support cgroup rt period"
Oct 03 15:58:25 CyphonSOC dockerd[837]: time="2020-10-03T15:58:25.810975825Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Oct 03 15:58:25 CyphonSOC dockerd[837]: time="2020-10-03T15:58:25.813509381Z" level=info msg="Loading containers: start."
Oct 03 15:58:26 CyphonSOC dockerd[837]: time="2020-10-03T15:58:26.029771571Z" level=info msg="Default bridge (docker0) is assigned with an IP ad
Oct 03 15:58:26 CyphonSOC dockerd[837]: time="2020-10-03T15:58:26.069883271Z" level=info msg="Loading containers: done."
Oct 03 15:58:26 CyphonSOC dockerd[837]: time="2020-10-03T15:58:26.146078002Z" level=info msg="Docker daemon" commit=c97c6d6 graphdriver(s)=overl
Oct 03 15:58:26 CyphonSOC dockerd[837]: time="2020-10-03T15:58:26.146983524Z" level=info msg="Daemon has completed initialization"
Oct 03 15:58:26 CyphonSOC systemd[1]: Started Docker Application Container Engine.
Oct 03 15:58:26 CyphonSOC dockerd[837]: time="2020-10-03T15:58:26.157143690Z" level=info msg="API listen on /var/run/docker.sock"
root@CyphonSOC:/home/soc#

I tried to start it manually but same error, docker seems working fine. Is this issue expected or a system glitch.

**Comment by fatalglitch** [comment]
Sorry, this project is no longer actively maintained.
